### ISSUE TITLE
Missing ant-design-blazor.css

### ISSUE THREAD

**Issue by filipgoris** [Append-IT/ant-design-blazor#13]
### Symptoms

- After installation of the package and including a Button component on the page, the button shows up but is not styled.
- `https://localhost:10942/_content/ant-design-blazor/css/ant-design-blazor.css` produces 404.

### Notes
- ASP.Net Core 3.1
- Blazor Server-Side
- dotnet --version  
  3.1.300-preview-015048
- _In Host.cshtml <head>:
  `<link href="_content/ant-design-blazor/css/ant-design-blazor.css" rel="stylesheet">`

PS: Stylesheets of other component libraries (Blazored) are found.

**Comment by vertonghenb** [comment]
Thanks!
The correct css file is:
```html
<link href="_content/Append.AntDesign/css/ant-design-blazor.min.css" rel="stylesheet" />
```

the correct js files are:
```html
<script type="text/javascript" src="https://unpkg.com/@popperjs/core@2"></script><script type="text/javascript" src="_content/Append.AntDesign/js/interop.js"></script>
```

due note that the .js files will change in a future update so they're combined into 1.

**Comment by vertonghenb** [comment]
Small update:
.js files are now combined:
```html
  <link rel="stylesheet" href="_content/Append.AntDesign.Documentation/css/documentation-styles.min.css" />
  <script type="text/javascript" src="_content/Append.AntDesign/js/scripts.min.js"></script>
  <!-- Blazor Framework Script Here -->
```
